name: "Wine Tracker"
description: "FÃ¼r alle, die den Weinkeller im Griff haben wollen!"
version: "0.1.2"
slug: "wine_tracker"
url: "https://github.com/xenofex7/ha-wine-tracker"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
ports:
  5050/tcp: 5050
ports_description:
  5050/tcp: "Wine Tracker Web UI"
ingress: true
ingress_port: 5050
panel_icon: mdi:bottle-wine
panel_title: "Wine Tracker"
options: {}
schema: {}
map:
  - share:rw
